apiVersion: v1
kind: Service
metadata:
  name: jwt-auth-service
spec:
  type: NodePort
  selector:
    app: jwt-auth
  ports:
    - protocol: TCP
      port: 9100          # Porta interna del container su cui è in ascolto l'applicazione
      targetPort: 9100    # Porta target nel container
      nodePort: 30010     # Porta esterna esposta dal nodo per l'accesso esterno
